### ISSUE TITLE
Hegarty disables input

### ISSUE THREAD

**Issue by jacobhq** [jacobhq/allow-calc#1]
For some reason, hegarty disables the input when the extension activates. Any help would be appriciated!

**Comment by Diacius** [comment]
Its possible that hegarty detects code injection and blocks it. Maybe look into that?

**Comment by jacobhq** [comment]
It's not blocking the injection code itself, but hegarty is doing something to the input.

**Comment by Diacius** [comment]
The input box or the input changed in the file?

**Comment by Diacius** [comment]
Could you also give me intstructsions for installing the extention so i can test it on my end?

**Comment by jacobhq** [comment]
@Diacius On the webstore: https://chrome.google.com/webstore/detail/hegarty-allow-calculator/ompglifjmnnpmfoomlgonhoaehkbbndm. No input box is changed, but the extension does run a find and replace. See here: https://github.com/jacobhq/allow-calc/blob/main/src/inject.js at line 6.

**Comment by Diacius** [comment]
Is it possible, that the replacement works in a different way to how to expected it to. And is replacing something it shouldn’t?

**Comment by jacobhq** [comment]
It must be. I ran it without the replace, and all was fine.

**Comment by jacobhq** [comment]
I'm gonna close this, as I've found the cause.

**Comment by Diacius** [comment]
Just wondering, what was it changing that it shouldn't have?

**Comment by jacobhq** [comment]
@Diacius I ran a diff check before and after the change￼, and noting changed in the code, but the input seemed to work again. I'm moving this issue to issue #2.
